# IntelliJ Platform Properties
platformType = IC
platformVersion = 2024.3.5

# Plugin Properties
pluginGroup = com.ijson
pluginName = IJSON
pluginVersion = 1.0.0
pluginSinceBuild = 243
pluginUntilBuild = 253.*

# Gradle Properties
org.gradle.jvmargs = -Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true
